### ISSUE TITLE
Running portable ruby build with docker image on mac os x fails test for `/home/linuxbrew/.linuxbrew/bin/brew linkage homebrew/portable-ruby/portable-ruby`

### ISSUE THREAD

**Issue by cmbernard333** [Homebrew/homebrew-portable-ruby#80]
The following stack trace pops up on Mac OS X Mojave when building the portable ruby using the docker image on `master`:

Docker build:

```
docker build -f docker/Dockerfile.x86_64 -t homebrew-portable .
```

Docker run:

```
docker run --name=homebrew-portable-ruby -w /bottle homebrew-portable brew portable-package ruby
```

Stack trace:

```
Testing homebrew/portable-ruby/portable-ruby
==> /home/linuxbrew/.linuxbrew/bin/brew linkage homebrew/portable-ruby/portable-ruby
Error: homebrew/portable-ruby/portable-ruby: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </Homebrew libraries/> expected to not match
<"System libraries:\n  /lib64/ld-linux-x86-64.so.2\nHomebrew libraries:\n  /home/linuxbrew/.linuxbrew/lib/libc.so.6 (glibc)\n  /home/linuxbrew/.linuxbrew/lib/libcrypt.so.1 (glibc)\n  /home/linuxbrew/.linuxbrew/lib/libdl.so.2 (glibc)\n  /home/linuxbrew/.linuxbrew/lib/libm.so.6 (glibc)\n  /home/linuxbrew/.linuxbrew/lib/libpthread.so.0 (glibc)\n  /home/linuxbrew/.linuxbrew/lib/libutil.so.1 (glibc)\n">.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:55:in `block in assert_block'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:1627:in `_wrap_assertion'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:53:in `assert_block'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:715:in `block in assert_not_match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:1627:in `_wrap_assertion'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:708:in `assert_not_match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:737:in `block in assert_no_match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:1632:in `_wrap_assertion'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:733:in `assert_no_match'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-portable-ruby/Abstract/portable-formula.rb:30:in `test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1724:in `block (3 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:476:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1723:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:864:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1722:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1961:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1960:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1716:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
Error: Failure while executing; `brew test portable-ruby` exited with 1.
```

**Comment by MikeMcQuaid** [comment]
Is this different to https://github.com/Homebrew/homebrew-portable-ruby/issues/74?

**Comment by cmbernard333** [comment]
Looks very similar. They both fail during linkage. I encountered this issue when I was trying to do a test for [#59521](https://github.com/Homebrew/homebrew-cask/pull/59521)

**Comment by sjackman** [comment]
Why are you trying to rebuild `portable-ruby`?

**Comment by cmbernard333** [comment]
It's used in the github actions for `homebrew-core` and `hombrew-cask` so I wanted a local copy to try and execute my new `main.workflow` locally to see if it had been implemented correctly. See [#59521](https://github.com/Homebrew/homebrew-cask/pull/59521)

**Comment by sjackman** [comment]
Is it the Docker image, or the `portable-ruby` bottle that you want to build? You can download the `portable-ruby` bottle from Bintray. See https://bintray.com/homebrew/bottles-portable-ruby/portable-ruby#files

**Comment by MikeMcQuaid** [comment]
Closing in favour of 
https://github.com/Homebrew/homebrew-cask/pull/59521

**Comment by sjackman** [comment]
If you're looking for a Docker image, try `linuxbrew/brew`. http://hub.docker.com/r/linuxbrew/brew
